# Generated by Django 4.0 on 2022-03-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='details',
        ),
    ]
